### ISSUE TITLE
Error when filtering with no username in Orders List

### ISSUE THREAD

**Issue by mchesterkadwell** [latera/homs#79]
Hi, we are trying out Homs using a fresh install of the Docker images, with only a few changes made (a few new users, new orders etc.) for testing purposes.

**Steps to reproduce**
Remove all the tags in the username field of the Orders List. Press search.
![screenshot from 2018-02-15 13-56-42](https://user-images.githubusercontent.com/5013576/36308840-2a54dc06-131a-11e8-8c11-a91c90dd5799.png)

**Error**
![screenshot from 2018-02-16 12-18-40](https://user-images.githubusercontent.com/5013576/36308854-3a56b7d2-131a-11e8-83c5-e5b650e37c04.png)

Thanks for your help.

**Comment by sugarfree1** [comment]
Hello, @mchesterkadwell 
Thanks for your report! Bug is reproduced and confirmed. We are going to fix it soon.

BTW: To show orders with empty user field you need to select `Empty` user in `User name` field and click `Search` button.

**Comment by mchesterkadwell** [comment]
Thanks for your quick reply!

When a user has removed the Empty tag, it does not seem to be possible to get it back again:
![screenshot from 2018-02-16 13-59-39](https://user-images.githubusercontent.com/5013576/36310991-b0b47d4a-1321-11e8-895e-81402abbee2b.png)

You have to reload the page to get it back again.

**Comment by sugarfree1** [comment]
Actually `Empty` is not a real user. It's a special value to represent an empty user. That's why it's not found when you type `Empty`. You can add `Empty` tag if your click on `Not set` value. This is the only way and is not a bug.

![image](https://user-images.githubusercontent.com/1773010/36315369-8e11e8e6-1348-11e8-8df2-bd5ed35c2814.png)

leads to

![image](https://user-images.githubusercontent.com/1773010/36315391-9d8ba906-1348-11e8-9749-bdc47588cd91.png)

**Comment by sugarfree1** [comment]
BTW we are going to change `Not set` text to `Empty`.
